### ISSUE TITLE
Default Branch Deleted - Change Needed

### ISSUE THREAD

**Issue by ElliotPsyIT** [RedBullet/angular-component-library#1]
Trying to clone this repo results in:
```
git clone https://github.com/RedBullet/angular-component-library.git
Cloning into 'angular-component-library'...
remote: Counting objects: 1256, done.
remote: Compressing objects: 100% (633/633), done.
remote: Total 1256 (delta 586), reused 1256 (delta 586), pack-reused 0
Receiving objects: 100% (1256/1256), 467.09 KiB | 817.00 KiB/s, done.
Resolving deltas: 100% (586/586), done.
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```
Not the final warning.  Apparently, the default branch for this repo has been deleted (MASTER is typically the default branch).  An administrator will need to go to this repo's settings here in Github and modify the default branch to the repo's only branch 'develop'.

Thanks!

**Comment by simonlewisjones** [comment]
Thanks Elliot, seems like there was a weird bug when we transferred across from Bitbucket. Should be working now :)

**Comment by ElliotPsyIT** [comment]
Very good Simon.  Yes, works now.  Thanks!
